name: "Production Grade Terraform"

on:
  workflow_dispatch:

jobs:
  plan:
    name: "Generate Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # We save the plan to a binary file called 'tfplan'
        run: terraform plan -input=false -out=tfplan

      - name: Upload Plan Artifact
        # This saves the 'tfplan' file so the next job can download it
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-file
          path: environments/dev/tfplan

  apply:
    name: "Manual Approval & Apply"
    needs: plan
    environment: dev  # This triggers the CTO's approval gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-file
          path: ./environments/dev/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # We apply the EXACT file we generated in the Plan job
        run: terraform apply -auto-approve tfplan